### ISSUE TITLE
Use diff from base to scan secrets instead all the repo

### ISSUE THREAD

**Issue by mapedraza** [mapedraza/workflows#1]
It is possible to use just the diff:

```yml
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository that triggered the workflow
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for diff purposes

      # Checkout the Gitleaks source code
      - name: Checkout Gitleaks
        uses: actions/checkout@v4
        with:
          repository: gitleaks/gitleaks
          ref: v8.21.1
          path: gitleaks-source  # Check out Gitleaks to a specific directory

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'  # Specify Go version to install

      # Build Gitleaks
      - name: Build Gitleaks
        run: |
          make -C gitleaks-source build  # Build Gitleaks from the gitleaks-source directory

      # Get the diff between the source and destination branch
      - name: Get diff from PR
        id: diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.head_ref }} > diff.patch

      # Run Gitleaks using the diff from the PR
      - name: Run Gitleaks on diff
        run: |
          cat diff.patch | gitleaks-source/gitleaks detect --source - --redact --stdin --report-format=sarif --report-path=results.sarif --log-level=debug

      # Upload the scan report as an artifact (optional)
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: results.sarif

      # Fail the build if Gitleaks detects any secrets
      - name: Check for leaks
        run: |
          # Check if there are any "results" in the SARIF JSON file
          leaks=$(jq '.runs[0].results | length' results.sarif)

          if [ "$leaks" -gt 0 ]; then
            echo "Secrets detected in the PR!"
            jq '.runs[0].results[] | {message: .message.text, file: .locations[0].physicalLocation.artifactLocation.uri, line: .locations[0].physicalLocation.region.startLine}' results.sarif
            exit 1
          else
            echo "No secrets detected in PR."
          fi
```
